version: "3.0"
services:
  database:
    image: amsterdam/database
    ports:
      - "5403:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: schoonmonitor
      POSTGRES_USER: schoonmonitor
  web:
    build: ./web
    ports:
      - "8117:8001"
    links:
      - database:database
    environment:
      DB_NAME: schoonmonitor
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "schoonmonitor.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/schoonmonitor/static=/static"
  importer:
      build: ./importer
      links:
        - database:database
      volumes:
        - ./data:/data
      environment:
        DATABASE_NAME: schoonmonitor
        DATABASE_USER: schoonmonitor
        DATABASE_PASSWORD: insecure
        # Following are secret, should be provided as environment variables.
        EXTERN_DATASERVICES_PASSWORD:
      command: >
        bash -c "/app/run_import.sh \
               && /app/run_additional_sql.sh"
  cmsdownloader:
      build: ./cmsdownloader
      links:
        - database:database
      volumes:
        - ./data:/data
      environment:
        DATABASE_NAME: schoonmonitor
        DATABASE_USER: schoonmonitor
        DATABASE_PASSWORD: insecure
        # Following are secret, should be provided as environment variables.
        EXTERN_DATASERVICES_PASSWORD:
      command: >
        bash -c "/app/run_cmsdownloader.sh" \
              && "/app/run_load_json2pg.sh"

