# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 01:51
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beeldmaatlat',
            fields=[
                ('crid', models.AutoField(primary_key=True, serialize=False)),
                ('Schouwronde', models.CharField(max_length=255)),
                ('Volgnummer_inspectie', models.CharField(max_length=255)),
                ('Volgnummer_score', models.CharField(max_length=128)),
                ('Aanmaakdatum_score', models.DateTimeField(default=datetime.datetime.now)),
                ('Inspecteur', models.CharField(max_length=128)),
                ('Bestekspost', models.CharField(max_length=255)),
                ('Score', models.CharField(max_length=4)),
                ('brtk2015', models.CharField(max_length=4)),
                ('verblijfin', models.CharField(max_length=1)),
                ('bc2015', models.CharField(max_length=3)),
                ('Stadsdeel', models.CharField(max_length=128)),
                ('geb22', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=128)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=8)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=8)),
                ('meetgebied', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
            options={
                'get_latest_by': 'Aanmaakdatum_score',
            },
        ),
        migrations.CreateModel(
            name='Melding',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('meldingnummer', models.CharField(blank=True, max_length=15)),
                ('Buurtcode', models.CharField(blank=True, max_length=4)),
                ('Stadsdeelcode', models.CharField(blank=True, max_length=1)),
                ('Afhandeltermijn', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3)),
                ('Buurtnaam', models.CharField(max_length=255)),
                ('Datummelding', models.DateField(default=datetime.datetime.now)),
                ('Hoofdrubriek', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('Straat', models.CharField(max_length=255)),
                ('Subrubriek', models.CharField(max_length=255)),
                ('Trefwoord', models.CharField(max_length=255)),
                ('Geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
